import "../styles/main.scss";
import "../global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import NextTopLoader from "nextjs-toploader";
import { Providers } from "../providers/NextUiprovider";
import SignoutButton from "@/ListingApp/components/auth/signout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      </Head>
      <body>
        <Providers>
          <header className="flex justify-end gap-4 p-4 bg-gradient-to-b from-blue-900 to-black shadow">
            <SignoutButton />
          </header>
          <NextTopLoader color="black" crawl={true} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
